version: '2.3'

services:
  app:
    build:
      context: .
      dockerfile: packages/data-service/Dockerfile
    ports:
      - '${PORT:-3003}:${PORT:-3003}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3003}
      - HOST=${HOST:-0.0.0.0}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-shop_service_db}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-shop_service_db}
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID:-shop-service}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-shop-service}
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    # volumes:
    # - ./packages/data-service:/app/packages/data-service - for development
    networks:
      - shop_network

  db:
    image: postgres:16-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-shop_service_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-shop_service_db}']
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_DATA_DIR: /tmp/zookeeper/data
      ZOOKEEPER_LOG_DIR: /tmp/zookeeper/log
    networks:
      - shop_network
    # healthcheck:
    #   test: echo stat | nc localhost 2181
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      - shop_network
    # healthcheck:
    #   test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:

networks:
  shop_network:
    driver: bridge
