version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-todo_db}
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - CORS_ORIGIN=${CORS_ORIGIN:-true}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-todo_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
