version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: packages/shop-service/Dockerfile
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-shop_service_db}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-shop_service_db}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./packages/shop-service:/app/packages/shop-service
      - /app/node_modules
      - /app/packages/shop-service/node_modules
    networks:
      - shop_network

  db:
    image: postgres:16-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-shop_service_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-shop_service_db}']
      interval: 5s
      timeout: 5s
      retries: 5

    broker:
      image: kafka:4.0.0
      ports:
        - '${KAFKA_PORT:-9092}:9092'
      environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
        - KAFKA_BROKER_ID=1

volumes:
  postgres_data:

networks:
  shop_network:
    driver: bridge
